### ISSUE TITLE
tiger0421/docker-opencv-cuda:4.1.1 cannot be found...

### ISSUE THREAD

**Issue by a954217436** [tiger0421/docker-YOLOv4-cuda#1]
Would u plz upload tiger0421/docker-opencv-cuda:4.1.1 to the dockerhub? Thanks...

**Comment by tiger0421** [comment]
I uploaded it.
However, I built this container for Compute  Capability=7.5, so check your GPU [here](https://developer.nvidia.com/cuda-gpus#compute)
Thank you.
